import { Open_Sans } from "next/font/google";
import "react-phone-number-input/style.css";
import type { Metadata } from "next";
import { OpenSans } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={OpenSans.className}>
        {children}
        <div id="modal-root" />
      </body>
    </html>
  );
}
